# Generated by Django 3.1.7 on 2021-08-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='subject',
        ),
    ]
